### ISSUE TITLE
ImportError: mmdet/core/nms/nms_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_S2_

### ISSUE THREAD

**Issue by harrytrinh2** [zhengye1995/Zero-shot-Instance-Segmentation#10]
I am reproducing this work using the latest `mmdet` version. 
Inside the file `barpn_head.py`, I need to import `nms` from `ops` (`from mmdet.ops import nms`). However, in the new architecture of `mmdet`, there is no folder named `ops` inside `mmdet`, therefore, I copied the whole `nnm` folder from the old `mmdet` version. And I got this error: `ImportError: mmdet/core/nms/nms_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_S2_ #10`. That is because these two lines inside `nns_wrapper.py":

```
from . import nms_cpu, nms_cuda
from .soft_nms_cpu import soft_nms_cpu
```
It is failed to load these modules from the following files:
1. `nms_cpu.cpython-37m-x86_64-linux-gnu.so`
2. `nms_cuda.cpython-37m-x86_64-linux-gnu.so`
3. `soft_nms_cpu.cpython-37m-x86_64-linux-gnu.so`

Do you know how to get away with this problem? Note that in the new `mmdet` version, it does not have `ops` folder after compiling from mmcv

**Comment by zhengye1995** [comment]
The operations in ops have been moved into mmcv package, if you need to use nms, you can import it from mmcv, see https://github.com/open-mmlab/mmcv/blob/bf2c9fa8d21e4af903769b3d7aca20452e4b4669/mmcv/ops/nms.py

**Comment by harrytrinh2** [comment]
Very correct! How did you know it has been moved to mmcv?

**Comment by zhengye1995** [comment]
I am a super fan for mmlab, especially for mmdetection. I have won many awards in object detection competitions using mmdetection.

**Comment by harrytrinh2** [comment]
Hehe, good for you! This framework is very hard to understand how it works under the hood, but once you get the idea, it'd be very lovely then :)
