### ISSUE TITLE
Is train dataset config is correct? 

### ISSUE THREAD

**Issue by frkake** [zhengye1995/Zero-shot-Instance-Segmentation#11]
Below train config setting is correct?
It looks ignoring seen classes even during training. 
I wonder why this data class is called during training. 

https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/configs/zsi/65_15/train/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_65_15_decoder_notanh.py#L141

https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/configs/zsi/48_17/train/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_decoder.py#L142

I think that [CocoDataset_48_17](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/datasets/coco_48_17.py#L9) and [CocoDataset_65_15](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/datasets/coco_65_15.py#L9) data class looks appropriate. 

Thank you a lot!

**Comment by zhengye1995** [comment]
Sorry for this  confusing code. In fact, it only affects the category name during visualization.The data and categories used for training are completely determined by the label file https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/configs/zsi/48_17/train/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_decoder.py#L176. (note: 'dataset_type' affects training in the new version of mmdetection, but  has no effect in this old version)

**Comment by frkake** [comment]
@zhengye1995 
Thank you so much for fast response! 
I'm convinced very well! 

By the way, what version of mmdetection is based in this repository?
I would like to develop this in upper version of it.

**Comment by zhengye1995** [comment]
mmcv                   0.2.14              
mmdet                  1.0rc0+45ee140

**Comment by frkake** [comment]
@taku-buntu Thank you so much!
