### ISSUE TITLE
some problem of dataset

### ISSUE THREAD

**Issue by KainingYing** [zhengye1995/Zero-shot-Instance-Segmentation#13]
I have some questions about the dataset. In Section 5.1, you said that.
![image](https://user-images.githubusercontent.com/42159793/126272214-5bc3f681-d298-4ec9-9375-e5cb9b79c546.png)
Once the train image has the unseen class instance, this image will be discard. However,  in the code of your object, this [line](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/datasets/coco_unseen17.py#L65) shows that the unseen class instance is only discard in the image. The image will be preserved in the training. It really confuses me! 
BTW, how can get a visualization of a single image or a directory of images? 
many thanks.

**Comment by zhengye1995** [comment]
Sorry for this  confusing comment and you can ignore it which is used for my older version code.

In fact,  the label files currently given were obtained through the data processing procedure described in the paper. In training label file: instances_train2014_seen_48_17.json, all the images which contain unseen objects has been removed.

The data and categories used for training are completely determined by the filtered label file https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/configs/zsi/48_17/train/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_decoder.py#L176.

**Comment by KainingYing** [comment]
Thanks for your reply. I will check for this.
