### ISSUE TITLE
Where do functions locate in your code?

### ISSUE THREAD

**Issue by algoteam5** [zhengye1995/Zero-shot-Instance-Segmentation#15]
I have read your paper. I have some questions regarding Figure 3. 
- First, I don't understand where do you implement T_e, T_d (from Figure 3) in your code? 
- Where do you implement the regression branch (also in Figure 3)? 
- And where is the semantic feature getting from T_e and T_d and how do you use it as the input with W_s, W_u?
Could you please answer my questions using your code? Where are they implemented? Thank you

**Comment by zhengye1995** [comment]
Hi.
1. [T_e](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/bbox_heads/bbox_head_semantic.py#L84), [T_d](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/bbox_heads/convfc_bbox_semantic_head.py#L81)
2. [regression branch](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/bbox_heads/convfc_bbox_semantic_head.py#L102) 
3. [forward process](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/bbox_heads/convfc_bbox_semantic_head.py#L190)

**Comment by algoteam5** [comment]
Thank you, but I am getting overwhelmed by your work. There are so many things. Could you please specify the flow of your work. 
For example, First the model run detection by running `zero_shot_two_stage`, and then `convfc_bbox_semantic_head` is used to create bounding box etc...

**Comment by zhengye1995** [comment]
Since this repo is based on mmdetection, I suggest you to study the official documentation of mmdetection first, and then you can understand the code smoothly.
