### ISSUE TITLE
What is the use of voc file(vocabulary_w2v.txt)?

### ISSUE THREAD

**Issue by KainingYing** [zhengye1995/Zero-shot-Instance-Segmentation#17]
I am confused with what use of the voc file. Many thanks.

**Comment by zhengye1995** [comment]
This is the word2vec for the  tags in [NUS-WIDE](https://lms.comp.nus.edu.sg/wp-content/uploads/2019/research/nuswide/NUS-WIDE.html), which can be used as a supplement to existing semantic information. 

NUS-WIDE has 5018 unique tags, and the tag which related to the coco categories have been removed.

**Comment by harrytrinh2** [comment]
@zhengye1995 How are both images and text features embedded? It would be nice if you can explain that and show us the code of that.

**Comment by zhengye1995** [comment]
In detector:
1. [image features embedded](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/bbox_heads/convfc_bbox_semantic_head.py#L191)
2. [NUS-WIDE](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/bbox_heads/convfc_bbox_semantic_head.py#L199)
3. [raw word2vec](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/bbox_heads/convfc_bbox_semantic_head.py#L213)

In maske head:
1. [image features embedded](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/mask_heads/semantic_fcn_mask_head.py#L198)
2. [raw word2vec](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/mask_heads/semantic_fcn_mask_head.py#L210)

**Comment by harrytrinh2** [comment]
Thank you
