### ISSUE TITLE
Where are the hooks among classes?

### ISSUE THREAD

**Issue by algoteam5** [zhengye1995/Zero-shot-Instance-Segmentation#19]
In your config file for train 65, I can see a class order like this:
`ZeroShotMaskRCNN` -> `BackgroundAwareRPNHead` -> `SharedFCSemanticBBoxHead` - > `SemanticFCNMaskHead`

They are classes located in `mmdet/models`, where are the hook functions that connect among those classes?

**Comment by zhengye1995** [comment]
See this [code](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/apis/train.py#L143), the mmcv runner hooks  all these components.

**Comment by algoteam5** [comment]
So they are processed in order right? and what if I just want to run `ZeroShotTwoStageDetector` only? how would I change?

**Comment by zhengye1995** [comment]
In fact, ZeroShotTwoStageDetector is composed of Backbone, BackgroundAwareRPNHead, SharedFCSemanticBBoxHead and SemanticFCNMaskHead.  Just like mask rcnn is also composed of similar modules.

**Comment by algoteam5** [comment]
"In fact, ZeroShotTwoStageDetector is composed of Backbone, BackgroundAwareRPNHead, SharedFCSemanticBBoxHead and SemanticFCNMaskHead." 
I checked the `zero_shot_two_stage.py` file and I didn't see where did you call these functions `BackgroundAwareRPNHead`, `SharedFCSemanticBBoxHead`.

**Comment by zhengye1995** [comment]
> "In fact, ZeroShotTwoStageDetector is composed of Backbone, BackgroundAwareRPNHead, SharedFCSemanticBBoxHead and SemanticFCNMaskHead."
> I checked the `zero_shot_two_stage.py` file and I didn't see where did you call these functions `BackgroundAwareRPNHead`, `SharedFCSemanticBBoxHead`.

Please See:
In zero_shot_two_stage:
1. BackgroundAwareRPNHead:  [Instantiate](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/detectors/zero_shot_two_stage.py#L47),[Forward](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/detectors/zero_shot_two_stage.py#L184)

2. SharedFCSemanticBBoxHead: [Instantiate](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/detectors/zero_shot_two_stage.py#L50),[Forward](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/detectors/zero_shot_two_stage.py#L226)

3. SemanticFCNMaskHead: [Instantiate](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/detectors/zero_shot_two_stage.py#L55),[Forward](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/detectors/zero_shot_two_stage.py#L260)

**Comment by algoteam5** [comment]
Oh we don't need to directly call `BackgroundAwareRPNHead`, `SharedFCSemanticBBoxHead`? How does `builder` know we wanted to call `BackgroundAwareRPNHead` and `SharedFCSemanticBBoxHead` from Registry?

**Comment by zhengye1995** [comment]
Yes,  we don't need to directly call BackgroundAwareRPNHead, SharedFCSemanticBBoxHead. We pass the class name and the corresponding parameters from config file into  zero_shot_two_stage, the the builder uses the class name like `BackgroundAwareRPNHead` to build it, see the build code [here](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/utils/registry.py#L48).

**Comment by algoteam5** [comment]
You're awesome. I've got it. I was looking at the `registry.py` and was wondering that what is `shared_head` and how is it different from `head`?

**Comment by zhengye1995** [comment]
`shared_head` is a share head which is shared between `bbox_head` for detection and `mask_head` for instance segmentation.
