### ISSUE TITLE
Details of 48/17 and 65/15 datasets 

### ISSUE THREAD

**Issue by zhongxiangzju** [zhengye1995/Zero-shot-Instance-Segmentation#2]
Could you please give the details(id, label name) about two datasets used in paper which are 48/17 split and 65/15 split? Because it is needed to visualize coco format results. Thanks.

**Comment by zhengye1995** [comment]
For  48/17 split, the (id, label name) is in:
   1. 48 seen: https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/45ee140205ce1f4acaaa6e72ddb526c962068378/mmdet/datasets/coco_seen48.py#L10
   2. 17 unseen: https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/45ee140205ce1f4acaaa6e72ddb526c962068378/mmdet/datasets/coco_unseen17.py#L11
   3. 65 classes for GZSI: https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/45ee140205ce1f4acaaa6e72ddb526c962068378/mmdet/datasets/coco_65_15.py#L11

For 65/15 split:
    1. 65 seen: https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/45ee140205ce1f4acaaa6e72ddb526c962068378/mmdet/datasets/coco_seen65.py#L11
    2. 15 unseen: https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/45ee140205ce1f4acaaa6e72ddb526c962068378/mmdet/datasets/coco_unseen15.py#L11
    3.  80 classes for GZSI: https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/45ee140205ce1f4acaaa6e72ddb526c962068378/mmdet/datasets/coco_65_15.py#L11
