### ISSUE TITLE
Where do losses locate?

### ISSUE THREAD

**Issue by algoteam5** [zhengye1995/Zero-shot-Instance-Segmentation#21]
On page 6, you introduced 4 different losses. Where do they locate?

**Comment by zhengye1995** [comment]
Sorry for the late reply.

In detector:  [bbox loss (regression loss)](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/bbox_heads/bbox_head_semantic.py#L188); [Reconstruction loss](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/bbox_heads/bbox_head_semantic.py#L196); [semantic classification loss](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/bbox_heads/bbox_head_semantic.py#L174)

In mask head:  [mask loss](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/mask_heads/semantic_fcn_mask_head.py#L241); [Reconstruction loss](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/mask_heads/semantic_fcn_mask_head.py#L245)
