### ISSUE TITLE
Hardware environment

### ISSUE THREAD

**Issue by soongyuu** [zhengye1995/Zero-shot-Instance-Segmentation#25]
Thanks for your codes!
Do you have specific requirements for the hardware environment in which the program is running? My GPU is nvidia RTX24G. An out of memory error occurred during program execution.

**Comment by zhengye1995** [comment]
In this repo, I use nvidia Tesla P40 with 24GB memory.
I have aslo try nvidia RTX 2080Ti with 11GB memory, and I need to reduce the batchsize and learning rate by half.

**Comment by soongyuu** [comment]
Thank you for your reply. The program is running as per your configuration



At 2021-11-22 11:10:14, "zhengye" ***@***.***> wrote:

In this repo, I use nvidia Tesla P40 with 24GB memory.
I have aslo try nvidia RTX 2080Ti with 11GB memory, and I need to reduce the batchsize and learning rate by half.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
