### ISSUE TITLE
results/zsi_48_17.json

### ISSUE THREAD

**Issue by soongyuu** [zhengye1995/Zero-shot-Instance-Segmentation#26]
Why did my model not generate results/zsi_48_17.json file after training

**Comment by zhengye1995** [comment]
Hi, you should run testing process to generate it.

**Comment by soongyuu** [comment]
我直接用中文给你回复了
我发现在进行test的时候，必须要自己手动建立一个results/zsi_48_17.json的空白文件，这个时候运行test就可以正常了。不知道我的复现是否正确？不过还是感谢你不耐其烦的给我的回复，非常感谢。



At 2021-11-26 10:17:14, "zhengye" ***@***.***> wrote:

Hi, you should run testing process to generate it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhengye1995** [comment]
> 我直接用中文给你回复了 我发现在进行test的时候，必须要自己手动建立一个results/zsi_48_17.json的空白文件，这个时候运行test就可以正常了。不知道我的复现是否正确？不过还是感谢你不耐其烦的给我的回复，非常感谢。 At 2021-11-26 10:17:14, "zhengye" ***@***.***> wrote: Hi, you should run testing process to generate it. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我想到一个原因，测试生成的结果是存在results目录下，如果你一开始没有创建这个目录的确会出现没有保存成功的情况，所以你的操作其实不是有了results/zsi_48_17.json 文件work，而是因为你创建了 results/ 文件夹

**Comment by soongyuu** [comment]
原来如此，非常感谢。拜读了你的论文《zero-shot instance segmentation》对我启发很大，是一片集大成者的论文。后期准备仔细研究，有疑问可能还会麻烦你。



在 2021-11-26 10:31:09，"zhengye" ***@***.***> 写道：

我直接用中文给你回复了 我发现在进行test的时候，必须要自己手动建立一个results/zsi_48_17.json的空白文件，这个时候运行test就可以正常了。不知道我的复现是否正确？不过还是感谢你不耐其烦的给我的回复，非常感谢。 At 2021-11-26 10:17:14, "zhengye" @.***> wrote: Hi, you should run testing process to generate it. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我想到一个原因，测试生成的结果是存在results目录下，如果你一开始没有创建这个目录的确会出现没有保存成功的情况，所以你的操作其实不是有了results/zsi_48_17.json 文件work，而是因为你创建了 results/ 文件夹

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
