### ISSUE TITLE
Question about mmcv version

### ISSUE THREAD

**Issue by WindFall-wyx** [zhengye1995/Zero-shot-Instance-Segmentation#27]
When I evaluate,why I got this error? It seems that the mmcv version is wrong,but mmcv==0.2.14 is in your requirements.txt. I just installed the environment following your guide.
```
python tools/gzsi_coco_eval.py results/gzsi_48_17.bbox.json --ann data/coco/annotations/instances_val2014_gzsi_48_17.json --gzsi --num-seen-classes 48
Traceback (most recent call last):
  File "tools/gzsi_coco_eval.py", line 3, in <module>
    from mmdet.core import coco_eval
  File "/home/xxx/mmdetection/mmdet/__init__.py", line 24, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==0.2.14 is used but incompatible. Please install mmcv>=1.3.8, <=1.4.0.
```

**Comment by zhengye1995** [comment]
Please check do you have other version mmdet package in your python environment, and try to rebuild mmdet.
It looks like you are using a newer version of mmdet instead of the version of this repo.

**Comment by WindFall-wyx** [comment]
> Please check do you have other version mmdet package in your python environment, and try to rebuild mmdet. It looks like you are using a newer version of mmdet instead of the version of this repo.

Thanks！I was stupid.
