### ISSUE TITLE
Ablation Studies for ZSD

### ISSUE THREAD

**Issue by WindFall-wyx** [zhengye1995/Zero-shot-Instance-Segmentation#28]
I notice that the Semantic Mask Head can improve the performance of ZSD. In my mind，this component is used for instance segmentation. How can the SMH influence the ZSD. Could you explain it for me? And where is the code. Thanks a lot.

**Comment by zhengye1995** [comment]
The code of SHM is in [here](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/mmdet/models/mask_heads/semantic_fcn_mask_head.py)

The principle that SHM affects ZSD is consistent with the principle that mask head in Mask R-CNN can improve detection performance. The gradient generated by detection and instance segmentation as parallel training tasks can simultaneously supervise the learning of the previous model parameters.

**Comment by WindFall-wyx** [comment]
I got it.Thank you.%%%
