### ISSUE TITLE
Question about pre-trained word-vector

### ISSUE THREAD

**Issue by JKZhan** [zhengye1995/Zero-shot-Instance-Segmentation#29]
can you tell me how do you use extra semantic knowledge in pre-trained word-vectors to correlate the seen and unseen classes

**Comment by zhengye1995** [comment]
1. training phase: learn the relationship between visual features and word-vectors of seen classes
2. testing phase:  obtain unseen scores through visual features and  word-vectors of unseen classes

The correlation of seen and unseen classes is contained in the pre-trained word-vectors, e.g., given "cat", "dog" and "bus", "cat" and "dog" have higher word vector similarity
