### ISSUE TITLE
How to train BA-RPN?

### ISSUE THREAD

**Issue by zhongxiangzju** [zhengye1995/Zero-shot-Instance-Segmentation#3]
A vital important module in zero-shot instance segmentation framework is BA-RPN, background aware region proposal network, could you please introduce more details about how to train BA-RPN, such as the dataset used. In synchronized background strategy, is BA-RPN pretrained before then finetune, or the framework is trained from scratch? Thanks a lot !

**Comment by zhengye1995** [comment]
The framework is trained from scratch in an end-to-end manner.
