### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [300, 49]] is at version 4; expected version 3 instead

### ISSUE THREAD

**Issue by WindFall-wyx** [zhengye1995/Zero-shot-Instance-Segmentation#30]
`cls_score, bbox_pred, x_semantic, d_feature = self.bbox_head(bbox_feats, bg_vector=bg_vector[0].view([300,]))
                    sum_cls_score, sum_bbox_pred,sum_x_semantic,sum_d_feature = self.bbox_head(sum_feats, bg_vector=bg_vector[0].view([300, ]))`
`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [300, 49]] is at version 4; expected version 3 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).`
I used your bbox_head twice, it got this error. If with_syn_bg is closed, it functions well. How should i do to use it with syn_bg?

**Comment by zhengye1995** [comment]
I think this should be a problem of pytorch itself, you can find the discussion in [here](https://discuss.pytorch.org/t/encounter-the-runtimeerror-one-of-the-variables-needed-for-gradient-computation-has-been-modified-by-an-inplace-operation/836).
