### ISSUE TITLE
segfault in nms_cuda.cpython-37m-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by HaoyuLizju** [zhengye1995/Zero-shot-Instance-Segmentation#38]
**Describe the bug**
subprocess.CalledProcessError: Command '['/public/home/{username}/anaconda3/envs/zsi/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/zsi/65_15/train/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_65_15_decoder_notanh.py', '--launcher', 'pytorch']' died with <Signals.SIGSEGV: 11>.

And in the system log, it reports that:
[11500204.905633] python[214734]: segfault at b ip 00007f8b3b6fd41c sp 00007fff1df7e0a0 error 6 in nms_cuda.cpython-37m-x86_64-linux-gnu.so[7f8b3b6f1000+15000]

**Reproduction**
1. What command or script did you run?
```
"./tools/dist_train.sh configs/zsi/train/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_65_15_decoder_notanh.py 4"
```

**Environment**
 - OS: CentOS Linux release 7.9.2009
 - GCC: 7.3.0 and I also tried 11.2.0
 - PyTorch version [1.1.0]
- How you installed PyTorch [conda]
- GPU model [V100]
- CUDA 10.0

The mmdetetion's issue say it might caused by improper gcc version and I have tried gcc 7.3.0 /11.2.0, but the segfault still occur.

**Comment by zhengye1995** [comment]
gcc 7.3.0 is ok.

What is the mmcv version in your environment and did you build mmdetection  successfully.

**Comment by wisest-cui** [comment]
Do you have 4 GPU?  this digit means the number of GPU

**Comment by HaoyuLizju** [comment]
I solved this problem. For CentOS , g++ but not c++ is required to build the extension.
