### ISSUE TITLE
30 series gpu problem

### ISSUE THREAD

**Issue by JK6917** [zhengye1995/Zero-shot-Instance-Segmentation#39]
Hi does your code can run on mmdetion2.0 version ? I found that 30 gpu can just run on new version of mmcv and mmdet . I install the new version on official web site and pass the simple code , but i still can't run on your code. I found that you have setup.py in your file which is different to official version witch one i should use?

**Comment by zhengye1995** [comment]
I am sorry for that. This code is based on the old version of mmcv, it can be difficult to compile it under cuda11 to support 30 series graphics cards.

I believe that the safest thing to do is to migrate the logic in my code to the mmdetection2.0.
