### ISSUE TITLE
Performance question 

### ISSUE THREAD

**Issue by JKZhan** [zhengye1995/Zero-shot-Instance-Segmentation#43]
Did you set random seed in your code, i run the origin code but the performance is lower than your result

**Comment by zhengye1995** [comment]
I did not set the random seed, considering the sparse representation of semantics, there will be some volatility. By the way, I found that the 9-th or 11-th epoch may achieve better performance, the learning rate schedule in is this method directly reuses it in  traditional supervised learning of COCO dataset, which can be improved.

**Comment by JKZhan** [comment]
How many and witch gpu do you use in this paper ?

**Comment by zhengye1995** [comment]
4 GPU (total batchsize=8) with lr=0.01 or 8 GPU (total batchsize=16) with lr=0.02 are both ok. I used 2080Ti and P40 in this paper.

**Comment by JKZhan** [comment]
Thanks for reply
