### ISSUE TITLE
ImportError: from . import deform_conv_cuda

### ISSUE THREAD

**Issue by harrytrinh2** [zhengye1995/Zero-shot-Instance-Segmentation#5]
```
  File "/home/merge/Harry/instance_seg/ZSI/mmdet/ops/dcn/deform_conv.py", line 9, in <module>

ImportError: from . import deform_conv_cuda
```
While starting training, the model could not import from `deform_conv_cuda`. You are using `mmdetection` library and there's an issue which is similar to mine but it didn't work https://github.com/open-mmlab/mmdetection/issues/601

**Comment by zhengye1995** [comment]
Please check if the dependent package version is consistent with mine, like mmcv, pytorch, mmdet. (This repo uses a old version of mmdet.)

**Comment by harrytrinh2** [comment]
@zhengye1995 My dependent packages are exactly the same as yours except I'm using Cuda 11 instead of Cuda 10. Is there any chance to download the `deform_conv_cuda` function so that I don't need to reproduce the exact Cuda environment?

**Comment by harrytrinh2** [comment]
Or it could be a much better way for me to understand your work by showing me how do I run your work on a new version of `mmdet`?

**Comment by zhengye1995** [comment]
> Or it could be a much better way for me to understand your work by showing me how do I run your work on a new version of `mmdet`?

Sorry, I have not tried CUDA 11 so I don't know whether this old version of mmd can be compiled successfully on CUDA 11.

If you need to run it in new mmd version with CUDA 11, you need reimplement this work in the new version.

**Comment by harrytrinh2** [comment]
Could you please give me some guidelines showing me how to reproduce your work on the new version of `mmdet`?  How does your code structure?

**Comment by zhengye1995** [comment]
The core code of my work in mmdet:
- mmdet
     - datasets
         -  coco_48_17.py
         -  coco_65_15.py
         -  coco_unseen15.py
         -  coco_unseen17.py
     - models
         - detectors
             - zero_shot_two_stage.py
             - zero_shot_mask_rcnn.py
             - test_mixins.py
          - anchor_heads
              -  barpn_head.py.py
              - ba_anchor_head.py
          -  bbox_heads
              - convfc_bbox_semantic_head.py 
          - mask_heads
              - semantic_fcn_mask_head.py

**Comment by harrytrinh2** [comment]
This is very helpful. Thank you very much @zhengye1995 !!
